(deftheme alacritty-dark
  "Created 2020-09-30.")

(custom-theme-set-faces
 'alacritty-dark
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#000000" :foreground "#eaeaea" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "ADBO" :family "Source Code Pro"))))
 '(cursor ((t (:background "#eaeaea"))))
 '(fixed-pitch ((t nil)))
 '(variable-pitch ((t (:family "Source Code Pro"))))
 '(escape-glyph ((t (:foreground "#e7c547" :weight bold))))
 '(homoglyph ((t (:foreground "#e7c547" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#d54e53"))))
 '(highlight ((t (:background "#666666" :foreground "#eaeaea" :underline t))))
 '(region ((t (:extend t :background "#666666" :foreground "#ffffff"))))
 '(shadow ((t (:foreground "#666666"))))
 '(secondary-selection ((t (:extend t :background "#506d8f" :foreground "#eaeaea"))))
 '(trailing-whitespace ((t (:background "#ff3334"))))
 '(font-lock-builtin-face ((t (:foreground "#d54e53"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#666666"))))
 '(font-lock-constant-face ((t (:foreground "#ff3334"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#9ec400"))))
 '(font-lock-keyword-face ((t (:foreground "#7aa6da" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#b9ca4a"))))
 '(font-lock-type-face ((t (:foreground "#b9ca4a" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#70c0ba"))))
 '(font-lock-warning-face ((t (:foreground "#e7c547"))))
 '(button ((t (:background "#000000" :foreground "#eaeaea"))))
 '(link ((t (:foreground "#54ced6" :underline t))))
 '(link-visited ((t (:foreground "#b77ee0" :underline t))))
 '(fringe ((t (:background "#000000"))))
 '(header-line ((t (:background "#000000" :foreground "#eaeaea"))))
 '(tooltip ((t (:inherit variable-pitch :background "#eaeaea" :foreground "#000000"))))
 '(mode-line ((t (:background "#666666" :foreground "#ffffff"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#eaeaea" :style released-button)))))
 '(mode-line-inactive ((t (:background "#000000" :foreground "#eaeaea"))))
 '(isearch ((t (:background "#666666" :foreground "#ffffff"))))
 '(isearch-fail ((t (:background "#ff3334"))))
 '(lazy-highlight ((t (:background "#7aa6da" :foreground "#ffffff"))))
 '(match ((t (:background "royal blue"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'alacritty-dark)
